[package]
name = "smt"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
digest = "0.9.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

